### PR TITLE
Use new BK agent buildpack

### PR DESCRIPTION
**Pull request by bjeanes**
Buildpack: https://github.com/bjeanes/heroku-buildpack-buildkite-agent
- Sets name of agent based on the heroku `$DYNO` env var
- Uses latest _stable_ release automatically; caches fetches between builds if no new releases
- Always adds `heroku=true` metadata

We still need do duplicate the Procfile entry here which is a bit of a PITA because it hardcodes the install location for the agent, which I would have rather kept an implementation detail. If `--*-path` and `--bootstrap-script` can be configurable by an env var that they could be left out of the `Procfile` and the buildpack could add `buildkite-agent` somewhere on the `$PATH`, which would reduce the entry down to something like `buildkite-agent start --meta-data "heroku=true"`.

This doesn't (yet) move any of the SSH key stuff because the existing buildpacks to the trick well enough for now.

### CODE REVIEW

**Comment by toolmantim** [comment]
Nice!!!!

So there's a few things we need to get into that buildpack, including documentation and supporting metadata environment variables (passing `"heroku=true" on the command line means you can't add/remove metadata using env vars).

And I'd be happy to move it to `buildkite` org and add you as a team member, and add it to our official docs.

**Comment by bjeanes** [comment]
> (passing `"heroku=true" on the command line means you can't add/remove metadata using env vars).

I tested that and found the opposite. Are you sure that's still the case? I noticed the docs had multiple `--meta-data x=y --meta-data a=b` flags which gave me the idea...

**Comment by bjeanes** [comment]
> And I'd be happy to move it to buildkite org and add you as a team member, and add it to our official docs.

Sounds good to me. I saw you added me to an org team, but GH doesn't allow me transfer into the org without admin :. It might be easier to just create a new repo in the team and I'll push to it. The one on my account won't have any following yet, I suspect, but I can re-fork from the org just in case if there's any concern.

**EDIT**: actually maybe you just need to give me temporary perms to create repos in that team?

**Comment by keithpitt** [comment]
Sorry, it's my fault. @toolmantim asked me this morning meta data this morning, and I thought it had to be one or the other. Looks like I did some merge logic and forgot about it. So if you add something from the `ENV` as well as the command line for `BUILDKITE_AGENT_META_DATA`, they'll get merged.

**Comment by keithpitt** [comment]
@bjeanes if you make me admin of the build pack I could probably transfer?

**Comment by bjeanes** [comment]
@keithpitt it's a personal repo so there's only collaborators not admins. I'll try, but I doubt it'll work. Adding you now.

**Comment by bjeanes** [comment]
@keithpitt actually I could probably transfer it into your personal account, at which point you could move to org. LMK if xferring directly doesn't work for you.

**Comment by keithpitt** [comment]
I have no idea how GitHub works. I just repushed to ours and added you :)

**Pull request merged**
